In [ ]:
56  print("hi guys")

hi guys

In [ ]:
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
data = [1,2,3,4,5]
s=pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s= pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# with dict
cd=pd.Series({'s':21,'y':30})
print(cd)

s    21
y    30
dtype: int64

In [ ]:
#accesing index
import pandas as pd
data=['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[:6])

set[slice(None, 6, None)]

In [ ]:
import pandas as pd
data=['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[:-6])

set[slice(None, -6, None)]

In [ ]:
import pandas as pd
data=['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[6:])

set[slice(6, None, None)]

In [ ]:
import pandas as pd
data=['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[-6:])

set[slice(-6, None, None)]

In [ ]:
#updating
import pandas as pd
data=['g','r','r','h','k','u','o','p']
ser = pd.Series(data)
print(set[:6])
ser['z']=10
print(ser)

set[slice(None, 6, None)]
0     g
1     r
2     r
3     h
4     k
5     u
6     o
7     p
z    10
dtype: object

In [ ]:
#adding
s1= pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
s2 = pd.Series([10,20,30,40,50], index = ['a','b','c','d','e'])
print(s1.drop('a'))

b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#drop (it was dynamically drop)
s1= pd.Series()

In [ ]:
#1
student= pd.Series([78,85,92,67,88],index=[101,102,103,104,105])
print(student)
print(student[103])
student[104]=75
print(student)
student=student.drop(102)
student[106]=90
print(student)

101    78
102    85
103    92
104    67
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    90
dtype: int64

In [ ]:
#employee salaries
employee = pd.Series([3500,42000,38000,50000,45000],index=[1001,1002,1003,1004,1005])
print(employee)
employee[1003]=40000
employee=employee.drop(1002)
student[1006]=55000
print(student[:3])

1001     3500
1002    42000
1003    38000
1004    50000
1005    45000
dtype: int64
101    78
103    92
104    75
dtype: int64

In [ ]:
#product prices
import pandas as pd
product= pd.Series([500,250,1200,900,1500],index=['P101','P102','P103','P104','P105'])
print(product)
price_value = product['P103']
print(price_value)
product['P102']=800
product =product.drop('P104')

P101     500
P102     250
P103    1200
P104     900
P105    1500
dtype: int64
1200

In [ ]:
import pandas as pd
bank= pd.Series([25000,45000,32000,18000,60000],index=['A101','A102','A103','A104','A105'])
print(bank)
bank[A104]=25000
bank=bank.drop(A101)

A101    25000
A102    45000
A103    32000
A104    18000
A105    60000
dtype: int64

NameError: name 'A104' is not defined

DATA FRAMES  CRAETION

In [ ]:
#USING LIST
import pandas as pd
data = [
    ["ravi",20,30000],
    ["priya",24,40000],
    ["Arun",21,28000]
]
df = pd.DataFrame(data,columns=['name','age','salary'])
print(df)

    name  age  salary
0   ravi   20   30000
1  priya   24   40000
2   Arun   21   28000

In [ ]:
# using tuple
import pandas as pd
data = (
    ("ravi",20,30000),
    ("priya",24,40000),
    ("Arun",21,28000)
)
df = pd.DataFrame(data,columns=('name','age','salary'))
print(df)

    name  age  salary
0   ravi   20   30000
1  priya   24   40000
2   Arun   21   28000

In [ ]:
#using dict
import pandas as pd
data = {
    'Name' : ['Ravi','Priya','Arun'],
    'Age' : ['20','24','21'],
    'Salary' : ['30000','40000','28000']
}
df = pd.DataFrame(data)
print(df)

    Name Age Salary
0   Ravi  20  30000
1  Priya  24  40000
2   Arun  21  28000

In [ ]:
#create a dataframe sales and profit of every month the 1st 6 months in the year

import pandas as pd
sales = (
    ("jan",2500,3000),
    ("feb",3000,3500),
    ("march",4000,4500),
    ("april",3500,4000),
    ("may",6000,5500),
    ("june",5500,6000)
)
df = pd.DataFrame(sales,columns = ["month","sales","profit"])
print(df)

   month  sales  profit
0    jan   2500    3000
1    feb   3000    3500
2  march   4000    4500
3  april   3500    4000
4    may   6000    5500
5   june   5500    6000

In [ ]:
#creating dataframe from a set
import pandas as pd
my_set= {100,30,50,79}
df = pd.DataFrame(list(my_set),columns=['values'])
print(df)

   values
0      50
1     100
2      30
3      79

In [ ]:
#COnverting a series to a DataFrame
s = pd.Series(
    [1,2,3,4],
    name = 'numbers')
df = s.to_frame()#here single series cov we use s.to_frame
print(df)

   numbers
0        1
1        2
2        3
3        4

In [ ]:
#for multiple series converted into tuple
s2 = pd.Series([9,6,5,8])
s3 = pd.Series([12,13,14,15])
d = {
    "marks-A" :s,
    "marks-B" :s2,
    "marks-C" :s3
}
df = pd.DataFrame(d)
print(df)

   marks-A  marks-B  marks-C
0        1        9       12
1        2        6       13
2        3        5       14
3        4        8       15

In [ ]:
#Rename the columns
s = pd.Series(
    [1,2,3,4],
    name = 'numbers')
df = s.to_frame()#here single series cov we use s.to_frame
df.columns=['digits'] #rename the columns
print(df)

   digits
0       1
1       2
2       3
3       4

In [ ]:
s2 = pd.Series([9,6,5,8])
s3 = pd.Series([12,13,14,15])
d = {
    "marks-A" :s,
    "marks-B" :s2,
    "marks-C" :s3
}
df = pd.DataFrame(d)

   maths  science  hindhi
0      1        9      12
1      2        6      13
2      3        5      14
3      4        8      15

In [ ]:
#rename (permenently rename the column)
df.rename(columns={'maths': 'Alpha','science':'Beta'},inplace=True)
print(df)

   Alpha  Beta  hindhi
0      1     9      12
1      2     6      13
2      3     5      14
3      4     8      15

In [ ]:
#viewing Data
s2 = pd.Series([28,29,30,31])
s3 = pd.Series([76,89,65,34])
d = {
    "marks-A" : s,
    "marks-B" : s2,
    "marks-C" : s3
}
df = pd.DataFrame(d)
df.columns = ["python","da","mysql"]
print(df)
#viewing
print(df.head(4)) #head
print(df.tail(3)) #bottom
print(len(df))#length
print(df.shape)#shape
print(df.values)#values
df.index#indexing
df.values

   python  da  mysql
0       1  28     76
1       2  29     89
2       3  30     65
3       4  31     34
   python  da  mysql
0       1  28     76
1       2  29     89
2       3  30     65
3       4  31     34
   python  da  mysql
1       2  29     89
2       3  30     65
3       4  31     34
4
(4, 3)
[[ 1 28 76]
 [ 2 29 89]
 [ 3 30 65]
 [ 4 31 34]]

array([[ 1, 28, 76],
       [ 2, 29, 89],
       [ 3, 30, 65],
       [ 4, 31, 34]])

In [ ]:
import pandas as pd
data = [
    ["ravi",20,'hyd',30000],
    ["priya",24,'vzg',40000],
    ["Arun",21,'hyd',28000],
    ["sneha",23,'vzg',30000],
    ["harshi",34,'hyd',40000]
]
df = pd.DataFrame(data,columns=['name','age','city','salary'])
print(df)

     name  age city  salary
0    ravi   20  hyd   30000
1   priya   24  vzg   40000
2    Arun   21  hyd   28000
3   sneha   23  vzg   30000
4  harshi   34  hyd   40000

In [ ]:
#q2
import pandas as pd
data = (
    ("rice","food",2000,"25kg"),
    ("face cream","cosmetics",500,"1 pac"),
    ("chips","snacks",50,"2 pac"),
    ("choclate","food",100,"1 pac"),
    ("red gram","cerals",1000,"2pac")
)
df = pd.DataFrame(data,columns = ['product','category','price','quantity'])
print(df)

      product   category  price quantity
0        rice       food   2000     25kg
1  face cream  cosmetics    500    1 pac
2       chips     snacks     50    2 pac
3    choclate       food    100    1 pac
4    red gram     cerals   1000     2pac

In [ ]:
#q3
import pandas as pd
data = [
    (101,"bhagi","BCA",500),
    (102,"sneha","bsc",600),
    (103,"harshi","bcom",550),
    (104,"yashu","bsc",600),
    (105,"pravali","btech",580)

]
df = pd.DataFrame(data,columns = ['student_id','name','Course','marks'])
print(df)

   student_id     name Course  marks
0         101    bhagi    BCA    500
1         102    sneha    bsc    600
2         103   harshi   bcom    550
3         104    yashu    bsc    600
4         105  pravali  btech    580

In [ ]:
#selecting and filtering
import pandas as pd
data = {
    "name" : ["ravi","priya","Arun","sneha","kiran","Anjali","vikram","Meena"],
    "Age" : [22,24,21,25,23,26,20,27],
    "City" : ["Hyderabad","chennai","Banglore","Hydrerabad",
              "Mumbai","chennai","Banglore","Munabi"],
    "Salary" : [30000,40000,28000,50000,35000,45000,25000,55000]
}
df = pd.DataFrame(data,index = [101,102,103,104,105,106,107,108])
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())
print(len(df))
print(df.shape)
print(df.index)
print(df)
print(df[['name','Age']])
df.iloc[0:3]
df.loc[103]
df[df["Salary"]>45000]
df["Salary"]<35000

      name  Age        City  Salary
101   ravi   22   Hyderabad   30000
102  priya   24     chennai   40000
103   Arun   21    Banglore   28000
104  sneha   25  Hydrerabad   50000
105  kiran   23      Mumbai   35000
       name  Age        City  Salary
104   sneha   25  Hydrerabad   50000
105   kiran   23      Mumbai   35000
106  Anjali   26     chennai   45000
107  vikram   20    Banglore   25000
108   Meena   27      Munabi   55000
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 101 to 108
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      object
 1   Age     8 non-null      int64
 2   City    8 non-null      object
 3   Salary  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes
None
            Age        Salary
count   8.00000      8.000000
mean   23.50000  38500.000000
std     2.44949  10862.780491
min    20.00000  25000.000000
25%    21.75000  29500.000000
50%    23.50000  37500.000000
75%    25.25000  46250.000000
max    27.00000  55000.000000
8
(8, 4)
Index([101, 102, 103, 104, 105, 106, 107, 108], dtype='int64')
       name  Age        City  Salary
101    ravi   22   Hyderabad   30000
102   priya   24     chennai   40000
103    Arun   21    Banglore   28000
104   sneha   25  Hydrerabad   50000
105   kiran   23      Mumbai   35000
106  Anjali   26     chennai   45000
107  vikram   20    Banglore   25000
108   Meena   27      Munabi   55000
       name  Age
101    ravi   22
102   priya   24
103    Arun   21
104   sneha   25
105   kiran   23
106  Anjali   26
107  vikram   20
108   Meena   27

101     True
102    False
103     True
104    False
105    False
106    False
107     True
108    False
Name: Salary, dtype: bool

In [ ]:
import pandas as pd
data = {
    "student_id": [101,102,103,104,105,106,107,108,109,110],
    "name" : ["Aarav","Priya","Rahul","Sneha","Arjun",
              "Divya","Kiran","Ananya","Rohit","Meena"],
    "age" : [20,21,19,22,20,21,23,19,22,20],
    "course" : ["python","power Bi","python","Excel","python",
                "power Bi","Excel","python","power Bi","Excel"],
    "marks" : [85,78,92,67,88,74,81,95,69,90],
    "Attendance" : [92,85,96,78,89,82,91,98,75,94],
    "city" : ["hyderabad","chennai","banglore","hydreabad","pune",
              "chennai","hyderabad","bangalore","pune","hyderabad"]
}
df = pd.DataFrame(data)
print(df)#1
print(df.head())#2
print(df.tail(3))#3
print(df.info())#4
print(df['name'])#5
print(df[['name','course','marks']])#6
print(df[['student_id','age','Attendance','city']].loc[0:9])#7
print(df[['student_id','name','age','course','marks','Attendance','city']].loc[1:5])#8
print(df[['name','course','marks']].loc[0:4])#9
print(df[['name','marks','city']].loc[:6])#10
print(df[['name','course','city']].iloc[::107])#10
# Fixed the ValueError below by removing the outer df[...] wrapper
df[['student_id','name','age','course','marks','Attendance','city']].iloc[:3]#11
# Fixed the KeyError below by separating the column strings in the list
df[['name', 'course', 'marks']].iloc[1:5]#12
df[['student_id','name','age','course','marks','Attendance','city']].iloc[-3]#13
df[df["marks"]>80]#14

#(df[df["marks"]>80])$(df[df["Attendance"]>90])#15

   student_id    name  age    course  marks  Attendance       city
0         101   Aarav   20    python     85          92  hyderabad
1         102   Priya   21  power Bi     78          85    chennai
2         103   Rahul   19    python     92          96   banglore
3         104   Sneha   22     Excel     67          78  hydreabad
4         105   Arjun   20    python     88          89       pune
5         106   Divya   21  power Bi     74          82    chennai
6         107   Kiran   23     Excel     81          91  hyderabad
7         108  Ananya   19    python     95          98  bangalore
8         109   Rohit   22  power Bi     69          75       pune
9         110   Meena   20     Excel     90          94  hyderabad
   student_id   name  age    course  marks  Attendance       city
0         101  Aarav   20    python     85          92  hyderabad
1         102  Priya   21  power Bi     78          85    chennai
2         103  Rahul   19    python     92          96   banglore
3         104  Sneha   22     Excel     67          78  hydreabad
4         105  Arjun   20    python     88          89       pune
   student_id    name  age    course  marks  Attendance       city
7         108  Ananya   19    python     95          98  bangalore
8         109   Rohit   22  power Bi     69          75       pune
9         110   Meena   20     Excel     90          94  hyderabad
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  10 non-null     int64
 1   name        10 non-null     object
 2   age         10 non-null     int64
 3   course      10 non-null     object
 4   marks       10 non-null     int64
 5   Attendance  10 non-null     int64
 6   city        10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes
None
0     Aarav
1     Priya
2     Rahul
3     Sneha
4     Arjun
5     Divya
6     Kiran
7    Ananya
8     Rohit
9     Meena
Name: name, dtype: object
     name    course  marks
0   Aarav    python     85
1   Priya  power Bi     78
2   Rahul    python     92
3   Sneha     Excel     67
4   Arjun    python     88
5   Divya  power Bi     74
6   Kiran     Excel     81
7  Ananya    python     95
8   Rohit  power Bi     69
9   Meena     Excel     90
   student_id  age  Attendance       city
0         101   20          92  hyderabad
1         102   21          85    chennai
2         103   19          96   banglore
3         104   22          78  hydreabad
4         105   20          89       pune
5         106   21          82    chennai
6         107   23          91  hyderabad
7         108   19          98  bangalore
8         109   22          75       pune
9         110   20          94  hyderabad
   student_id   name  age    course  marks  Attendance       city
1         102  Priya   21  power Bi     78          85    chennai
2         103  Rahul   19    python     92          96   banglore
3         104  Sneha   22     Excel     67          78  hydreabad
4         105  Arjun   20    python     88          89       pune
5         106  Divya   21  power Bi     74          82    chennai
    name    course  marks
0  Aarav    python     85
1  Priya  power Bi     78
2  Rahul    python     92
3  Sneha     Excel     67
4  Arjun    python     88
    name  marks       city
0  Aarav     85  hyderabad
1  Priya     78    chennai
2  Rahul     92   banglore
3  Sneha     67  hydreabad
4  Arjun     88       pune
5  Divya     74    chennai
6  Kiran     81  hyderabad
    name  course       city
0  Aarav  python  hyderabad

   student_id    name  age  course  marks  Attendance       city
0         101   Aarav   20  python     85          92  hyderabad
2         103   Rahul   19  python     92          96   banglore
4         105   Arjun   20  python     88          89       pune
6         107   Kiran   23   Excel     81          91  hyderabad
7         108  Ananya   19  python     95          98  bangalore
9         110   Meena   20   Excel     90          94  hyderabad

In [ ]:
#Manupulating DAta
import pandas as pd
sales = pd.Series(
    [5000,7000,None,9000,8000,10000,None],
    index = [
        "Monday","Tuesday","Wednesday","Thursday",
        "Friday","Saturday","Sunday"])
print(sales)
#Aggregation
#sales["Tuesday"] = 9500
#print(sales)
sales=sales.drop("Tuesday")
print(sales.min())
print(sales.max())
print(sales.min())
print(sales.sum())
print(sales.var())
print(sales.std())
print(sales.dtype)#Check the data type
#Updating and inserion of new one
sales["jan"] = 7800
print(sales)
print(sales + 2000)
print(sales * 2)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64
5000.0
10000.0
5000.0
32000.0
4666666.666666667
2160.2468994692867
float64
Monday        5000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64
Monday        7000.0
Wednesday        NaN
Thursday     11000.0
Friday       10000.0
Saturday     12000.0
Sunday           NaN
jan           9800.0
dtype: float64
Monday       10000.0
Wednesday        NaN
Thursday     18000.0
Friday       16000.0
Saturday     20000.0
Sunday           NaN
jan          15600.0
dtype: float64

In [ ]:
s = pd.Series([1,2,3,4,5])#index=[9,7,6,8,0])
s1=pd.Series([101,102,103,104,105])#index=[901,902,903,904,905])
print(s)
print(s1)
c=pd.concat([s,s1],ignore_index=True)
print(c)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
5    101
6    102
7    103
8    104
9    105
dtype: int64

In [ ]:
import pandas as pd
data = {
    "name" : ["ravi","priya","Arun","sneha","kiran","Anjali","vikram","Meena"],
    "Age" : [22,24,21,25,23,26,20,27],
    "City" : ["Hyderabad","chennai","Banglore","Hydrerabad",
              "Mumbai","chennai","Banglore","Mumabi"],
    "Salary" : [30000,40000,28000,50000,35000,45000,25000,55000]
}
df = pd.DataFrame(data,index = [101,102,103,104,105,106,107,108])
print(df.head())
print(df["Age"].sum())
print(df['Salary'].min())
print(df["Age"].max())
print(df["Salary"].max())
print(df["Age"].sum())
print(df["Salary"].std())
print(df["Age"].std())
print(df["Salary"].count())
print(df["Age"].count())
print(df["Age"].var())
print(df["Salary"].median())
df['Bonus'] = df['Salary'] * 0.10
print(df)
df["newsalary"] = df["Salary"] + df["Bonus"]
print(df)
df["Age"] = df["Age"]+1
print(df)
df["newsalary"] = df["newsalary"]+500
df.loc[df['name'] == 'priya','city'] ='pune'
print(df)
df.loc[df['city'] == 'Banglore','City'] = 'Hydreabad'
print(df)
df.loc[df['City'] == 'Mumbai','Salary'] =df["Salary"]*1.05
print(df)
df.loc[df['Salary']<45000 ,"Salary"]=60000
print(df)
df.drop(
    'Bonus',
    axis=1,
    inplace=True
)
print(df)
df.drop(columns="newsalary",inplace=True)
print(df)

      name  Age        City  Salary
101   ravi   22   Hyderabad   30000
102  priya   24     chennai   40000
103   Arun   21    Banglore   28000
104  sneha   25  Hydrerabad   50000
105  kiran   23      Mumbai   35000
188
25000
27
55000
188
10862.780491200216
2.449489742783178
8
8
6.0
37500.0
       name  Age        City  Salary   Bonus
101    ravi   22   Hyderabad   30000  3000.0
102   priya   24     chennai   40000  4000.0
103    Arun   21    Banglore   28000  2800.0
104   sneha   25  Hydrerabad   50000  5000.0
105   kiran   23      Mumbai   35000  3500.0
106  Anjali   26     chennai   45000  4500.0
107  vikram   20    Banglore   25000  2500.0
108   Meena   27      Mumabi   55000  5500.0
       name  Age        City  Salary   Bonus  newsalary
101    ravi   22   Hyderabad   30000  3000.0    33000.0
102   priya   24     chennai   40000  4000.0    44000.0
103    Arun   21    Banglore   28000  2800.0    30800.0
104   sneha   25  Hydrerabad   50000  5000.0    55000.0
105   kiran   23      Mumbai   35000  3500.0    38500.0
106  Anjali   26     chennai   45000  4500.0    49500.0
107  vikram   20    Banglore   25000  2500.0    27500.0
108   Meena   27      Mumabi   55000  5500.0    60500.0
       name  Age        City  Salary   Bonus  newsalary
101    ravi   23   Hyderabad   30000  3000.0    33000.0
102   priya   25     chennai   40000  4000.0    44000.0
103    Arun   22    Banglore   28000  2800.0    30800.0
104   sneha   26  Hydrerabad   50000  5000.0    55000.0
105   kiran   24      Mumbai   35000  3500.0    38500.0
106  Anjali   27     chennai   45000  4500.0    49500.0
107  vikram   21    Banglore   25000  2500.0    27500.0
108   Meena   28      Mumabi   55000  5500.0    60500.0
       name  Age        City  Salary   Bonus  newsalary  city
101    ravi   23   Hyderabad   30000  3000.0    33500.0   NaN
102   priya   25     chennai   40000  4000.0    44500.0  pune
103    Arun   22    Banglore   28000  2800.0    31300.0   NaN
104   sneha   26  Hydrerabad   50000  5000.0    55500.0   NaN
105   kiran   24      Mumbai   35000  3500.0    39000.0   NaN
106  Anjali   27     chennai   45000  4500.0    50000.0   NaN
107  vikram   21    Banglore   25000  2500.0    28000.0   NaN
108   Meena   28      Mumabi   55000  5500.0    61000.0   NaN
       name  Age        City  Salary   Bonus  newsalary  city
101    ravi   23   Hyderabad   30000  3000.0    33500.0   NaN
102   priya   25     chennai   40000  4000.0    44500.0  pune
103    Arun   22    Banglore   28000  2800.0    31300.0   NaN
104   sneha   26  Hydrerabad   50000  5000.0    55500.0   NaN
105   kiran   24      Mumbai   35000  3500.0    39000.0   NaN
106  Anjali   27     chennai   45000  4500.0    50000.0   NaN
107  vikram   21    Banglore   25000  2500.0    28000.0   NaN
108   Meena   28      Mumabi   55000  5500.0    61000.0   NaN
       name  Age        City  Salary   Bonus  newsalary  city
101    ravi   23   Hyderabad   30000  3000.0    33500.0   NaN
102   priya   25     chennai   40000  4000.0    44500.0  pune
103    Arun   22    Banglore   28000  2800.0    31300.0   NaN
104   sneha   26  Hydrerabad   50000  5000.0    55500.0   NaN
105   kiran   24      Mumbai   36750  3500.0    39000.0   NaN
106  Anjali   27     chennai   45000  4500.0    50000.0   NaN
107  vikram   21    Banglore   25000  2500.0    28000.0   NaN
108   Meena   28      Mumabi   55000  5500.0    61000.0   NaN
       name  Age        City  Salary   Bonus  newsalary  city
101    ravi   23   Hyderabad   60000  3000.0    33500.0   NaN
102   priya   25     chennai   60000  4000.0    44500.0  pune
103    Arun   22    Banglore   60000  2800.0    31300.0   NaN
104   sneha   26  Hydrerabad   50000  5000.0    55500.0   NaN
105   kiran   24      Mumbai   60000  3500.0    39000.0   NaN
106  Anjali   27     chennai   45000  4500.0    50000.0   NaN
107  vikram   21    Banglore   60000  2500.0    28000.0   NaN
108   Meena   28      Mumabi   55000  5500.0    61000.0   NaN
       name  Age        City  Salary  newsalary  city
101    ravi   23   Hyderabad   60000    33500.0   NaN
102   priya   25     chennai   60000    44500.0  pune
103    Arun   22    Banglore   60000    31300.0   NaN
104   sneha   26  Hydrerabad   50000    55500.0   NaN
105   kiran   24      Mumbai   60000    39000.0   NaN
106  Anjali   27     chennai   45000    50000.0   NaN
107  vikram   21    Banglore   60000    28000.0   NaN
108   Meena   28      Mumabi   55000    61000.0   NaN
       name  Age        City  Salary  city
101    ravi   23   Hyderabad   60000   NaN
102   priya   25     chennai   60000  pune
103    Arun   22    Banglore   60000   NaN
104   sneha   26  Hydrerabad   50000   NaN
105   kiran   24      Mumbai   60000   NaN
106  Anjali   27     chennai   45000   NaN
107  vikram   21    Banglore   60000   NaN
108   Meena   28      Mumabi   55000   NaN

In [ ]:
#Cleaning
#to read the csv file ==> df = pd.read_csv("sales.csv") same as excel,json
#handling missing values
import pandas as pd
sales = pd.Series(
    [5000,7000,None,9000,8000,10000,None],
    index = [
        "Monday","Tuesday","Wednesday","Thursday",
        "Friday","Saturday","Sunday"])
print(sales)
sales.isnull()
sales.isna()
sales.isna().sum()
sales.dropna()
sales.fillna("no data")

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

Monday        5000.0
Tuesday       7000.0
Wednesday    no data
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday       no data
dtype: object

In [ ]:
import pandas as pd
employees = {
    "EmpID" : [101,102,103,104],
    "Name" : ["Asha",None,"Meena","Sai"],
    "Department" : ["Sales","It","HR",None],
    "Salary" : [45000,60000,None,89000]
}
I = [901,902,903,904]
df = pd.DataFrame(employees,index = I)
print(df)
#missing values
df.isna()
df.isna().sum()#count

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         It  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
# replace vth multiple rows
df.fillna({
    "Name" : "unkown",
    "Salary" : 0,
    "Department" : 0
})
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         It  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df ['Salary'].fillna(df['Salary'].max())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:

df['Salary'].fillna(df['Salary'].std())

901    45000.000000
902    60000.000000
903    22368.132093
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
import pandas as pd
employees = {
    "EmpID" : [101,102,103,104],
    "Name" : ["Asha",None,"Meena","Sai"],
    "Department" : ["Sales","It","HR",None],
    "Salary" : [45000,60000,None,89000]
}
I = [901,902,903,904]
df = pd.DataFrame(employees,index = I)
print(df)
df=df.head(2)#2
df=df.tail(2)
print([['Name',"Salary"]])#3
print(["EmpID"]==103)#4
df['Salary']>50000#5
df['Department']='IT'#6
df.isna()#7
df.isna().sum()#8
df.fillna({
    "Name" : "Unknown",
    "DEpartment" : "NotAssigned"
})#9
df["Bonus"] = df["Salary"] *0.1#10
df.loc[df['Name'] == 'Sai','Salary'] = 95000#11
df.rename(columns={"EmpID": "EmployeeId"}, inplace=True)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         It  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0
[['Name', 'Salary']]
False

In [ ]:
#multiple aggregations
import pandas as pd
employees = {
    "EmpID" : [101,102,103,104],
    "Name" : ["Asha",None,"Meena","Sai"],
    "Department" : ["Sales","It","HR",None],
    "Salary" : [45000,60000,None,89000]
}
I = [901,902,903,904]
df = pd.DataFrame(employees,index = I)
print(df)
df.isna()
df.isna().sum()
df=df.fillna({
    "Name" : "Bhagya",
    "DEpartment" : "HR",
    "Salary" : 600000
})
print(df)
df.groupby('Department')['Salary'].mean()#single aggregations
df.groupby('Department')['Salary'].max()
df.groupby('Department')['Salary'].min()
df.groupby('Department')['Salary'].count()
df.groupby('Department')['Salary'].agg(['min','max','mean'])#multiple aggregations
df.groupby('Department').agg({
    'EmpID' :['mean','max'],
    'Salary':['sum','count']
})

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         It  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0
     EmpID    Name Department    Salary
901    101    Asha      Sales   45000.0
902    102  Bhagya         It   60000.0
903    103   Meena         HR  600000.0
904    104     Sai       None   89000.0

            EmpID         Salary
             mean  max       sum count
Department
HR          103.0  103  600000.0     1
It          102.0  102   60000.0     1
Sales       101.0  101   45000.0     1

In [ ]:
import pandas as pd
data = {
    "name" : ["ravi","priya","Arun","sneha","kiran","Anjali","vikram","Meena"],
    "Age" : [22,24,21,25,23,26,20,27],
    "City" : ["Hyderabad","chennai","Banglore","Hydrerabad",
              "Mumbai","chennai","Banglore","Mumabi"],
    "Salary" : [30000,40000,28000,50000,35000,45000,25000,55000]
}
df = pd.DataFrame(data,index = [101,102,103,104,105,106,107,108])
print(df["name"]) #2
print(df[["name","Salary"]]) #3
df.loc[df["Age"]>23] #4
df.loc[df["Salary"]>40000] #5
df.loc[df["City"]=="chennai"] #6
df.loc[(df['Age'] > 22) & (df['Salary'] > 35000)]#7
df.loc[(df['City'] == 'Mumbai') | (df['City'] == 'Banglore')]#8
df.loc[df["Salary"]>35000,["name","Salary"]]#9
df.iloc[102:104]#10

101      ravi
102     priya
103      Arun
104     sneha
105     kiran
106    Anjali
107    vikram
108     Meena
Name: name, dtype: object
       name  Salary
101    ravi   30000
102   priya   40000
103    Arun   28000
104   sneha   50000
105   kiran   35000
106  Anjali   45000
107  vikram   25000
108   Meena   55000

Empty DataFrame
Columns: [name, Age, City, Salary]
Index: []

In [ ]:
import pandas as pd

data = {

   "TransactionID": [1001, 1002, 1003, 1004, 1005,

                      1006, 1007, 1008, 1009, 1010, 1010, 1011],

   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",

                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",

                "Sneha", "Kiran"],

   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",

               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",

               "Headphones", "Mouse"],

   "Amount": [55000, 25000, 30000, 5000, 1500,

              2500, 18000, 55000, 22000, 5000,

              5000, 1500]}

df= pd.DataFrame(data)

print(df)
df.duplicated()
df=df.duplicated()
count=df.duplicated().sum()
print(count)
a = df[df.duplicated()]
print(a)
a = df[df.duplicated()].sum

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
10
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
11    False
dtype: bool

In [ ]:
import pandas as pd

data = {
   "VisitID": [501, 502, 503, 504, 505,
               506, 507, 508, 509, 510, 510, 511],
   "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran",
               "Anjali", "Ravi", "Meena", "Arun", "Priya",
               "Priya", "Kiran"],
   "Department": ["Cardiology", "Neurology", "Orthopedic", "General",
                  "Dental", "Cardiology", "Neurology", "General",
                  "Dental", "Cardiology", "Cardiology", "Dental"],
   "BillAmount": [5000, 7500, 4500, 2000, 1500,
                  6000, 7000, 2500, 1800, 6000, 6000, 1500]}

df = pd.DataFrame(data)
print("--- Original DataFrame ---")
print(df)

# 1. Check duplicated rows

print(df.duplicated())



# 2 Find duplicate Patient VisitIDs
duplicates = df[df["VisitID"].duplicated(keep=False)]

print(duplicates)
#3
duplicates = df[df["VisitID"].duplicated(keep="first")]
print(duplicates)
#4
duplicates = df[df["BillAmount"].duplicated(keep="last")]
total = duplicates["BillAmount"].sum()
print(duplicates)

#5
duplicates = df[df["VisitID"].duplicated(keep="last")]
print(duplicates)
#6
duplicates = df[df.duplicated()]
print(duplicates)
#7
df = df.drop_duplicates(
   subset=["VisitID"],
   keep="first")
#8
df = df.drop_duplicates(
    subset=["Patient"],
    keep="first")
#9
df = df.drop_duplicates(subset=["Patient","Department"],keep = "first")
print(df)
#10
df.drop_duplicates(["VisitID"],keep="first")
print(df)

--- Original DataFrame ---
    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000
   VisitID Patient  Department  BillAmount
4      505   Kiran      Dental        1500
5      506  Anjali  Cardiology        6000
9      510   Priya  Cardiology        6000
   VisitID Patient  Department  BillAmount
9      510   Priya  Cardiology        6000
    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000
   VisitID Patient  Department  BillAmount
0      501   Rahul  Cardiology        5000
1      502   Anita   Neurology        7500
2      503  Suresh  Orthopedic        4500
3      504   Priya     General        2000
4      505   Kiran      Dental        1500
5      506  Anjali  Cardiology        6000
6      507    Ravi   Neurology        7000
7      508   Meena     General        2500
8      509    Arun      Dental        1800
   VisitID Patient  Department  BillAmount
0      501   Rahul  Cardiology        5000
1      502   Anita   Neurology        7500
2      503  Suresh  Orthopedic        4500
3      504   Priya     General        2000
4      505   Kiran      Dental        1500
5      506  Anjali  Cardiology        6000
6      507    Ravi   Neurology        7000
7      508   Meena     General        2500
8      509    Arun      Dental        1800